### ISSUE TITLE
Nanopore reads

### ISSUE THREAD

**Issue by mccartneya90** [a-ludi/dentist#1]
Heya,

I was just wondering if this could be utilised on nanopore assemblies? and if so what parameter I should specify for READ_TYPE in the snakemake.yml file.

Many thanks,
Ann

**Comment by a-ludi** [comment]
Hi Ann,

yes, it can be used with nanopore reads (and assemblies). Basically, you can specify anything other than `PACBIO_SMRT` but I would recommend using `OXFORD_NANOPORE` as NCBI does.


## Rationale

PacBio use a specific header format for their reads which is parsed by `fasta2DB`. Consequently, it cannot be applied to Nanopore-style FASTA files. As of now, the `read_type` parameter just determines whether to use `fasta2DB` or fasta2DAM` when converting the reads to a Dazzler DB.

**Comment by a-ludi** [comment]
A section about using nanopore reads should be added to the README.

**Comment by mccartneya90** [comment]
Brilliant! Thank you so much for all of the help and advice. I really appreciate how promptly you've gotten back to me on this.

A
________________________________
