### ISSUE TITLE
Snakefile: Line 334, dbsplit doesn't recognize the "-T" option

### ISSUE THREAD

**Issue by BradleyRan** [a-ludi/dentist#2]
344: dbsplit_flags = ensure_threads_flag(make_flags(config.get("dbsplit_flags", [])))

   results in   “-T is not a valid option for DBsplit”

suggest change:

344: dbsplit_flags = make_flags(config.get("dbsplit_flags", [])

**Comment by a-ludi** [comment]
Thanks for pointing this out! I fixed it according to your suggestion.
