### ISSUE TITLE
Missing Snakefile from example test dataset

### ISSUE THREAD

**Issue by davidjstudholme** [a-ludi/dentist#23]
I believe this is a distinct issue from https://github.com/a-ludi/dentist/issues/21 as it pertains to the Snakefile rather than the .yml files that you helpfully signposted. I am using the https://github.com/a-ludi/dentist-example/releases/download/v1.0.2-2/dentist-example.tar.gz example dataset.

When I execute
```(base) ubuntu@bio-xanthomonas:~/dentist-example$ snakemake --configfile=snakemake.yml --use-singularity --cores=all``` 
I get this error message: 
```Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.```

So, I guessed the obvious thing to do was to download this Snakefile: https://github.com/a-ludi/dentist/blob/develop/snakemake/Snakefile.

However, when I try again to execute the above command line, with this Snakefile in the current directory, I get:

```
IndentationError in line 113 of <tokenize>:
unindent does not match any outer indentation level (<tokenize>, line 113)
 File "/usr/lib/python3.8/tokenize.py", line 512, in _tokenize
```

I suspect, that this might be because I am not using the correct Snakefile?

**Comment by a-ludi** [comment]
> I suspect, that this might be because I am not using the correct Snakefile?

I agree. Try this [Snakefile](https://raw.githubusercontent.com/a-ludi/dentist/d85a86fda8da241b0de3d3b8d3b02cf9e3405302/snakemake/cluster.yml). It is the one that should be included in the tarball.

**Comment by davidjstudholme** [comment]
The link in your message above is: https://raw.githubusercontent.com/a-ludi/dentist/d85a86fda8da241b0de3d3b8d3b02cf9e3405302/snakemake/cluster.yml. This is file called 'cluster.yml' not 'Snakefile'. Is this intended?

**Comment by a-ludi** [comment]
This was a copy&paste mishap. Sorry. Correct link: https://raw.githubusercontent.com/a-ludi/dentist/d85a86fda8da241b0de3d3b8d3b02cf9e3405302/snakemake/Snakefile

**Comment by davidjstudholme** [comment]
Thanks, Arne.

However, with this file I now get this error message:
```
SyntaxError in line 896 of /home/djs217/dentist-example/Snakefile:
Unexpected keyword container in rule definition (Snakefile, line 896)
```

**Comment by davidjstudholme** [comment]
Possibly this is an issue with snakemake version used?

```
$ snakemake --version
5.10.0
```

**Comment by davidjstudholme** [comment]
The offending line 896 seems to be:

```    container: dentist_container
```

**Comment by a-ludi** [comment]
> Possibly this is an issue with snakemake version used?
Yes, please update to v5.32.1.

**Comment by davidjstudholme** [comment]
Thanks, Arne. So, I think the original issue is now resolved since the the missing file is available at: https://raw.githubusercontent.com/a-ludi/dentist/d85a86fda8da241b0de3d3b8d3b02cf9e3405302/snakemake/Snakefile
