### ISSUE TITLE
Singularity image is lacking a Python installation

### ISSUE THREAD

**Issue by a-ludi** [a-ludi/dentist#30]
Thanks to one of my users, I was made aware that the Singularity image should contain a Python installation to execute the Python rules.

**Comment by lautimothy** [comment]
hello,

May I ask if there's a quick way to provide python to the singularity workflow until the singularity image is updated?   I am currently stuck at the snakemake rule "make_merge_config" where it uses a python script.

Thanks,
Tim

**Comment by a-ludi** [comment]
Hi Tim,

I think the best way is for me to create a quick release with the bug fixed. I will prepare one in the next days.

If you want a quicker solution you may try fixing the image using the `--sandbox` and `--writable` options of Singularity (see [docs](https://docs.sylabs.io/guides/3.7/user-guide/build_a_container.html)). You will have to work out the details, though. 


Best,

Arne

**Comment by lautimothy** [comment]
Hi Arne,

Thank you for the prompt response.   I actually just got it working through installing through conda (both dentist and dentist-core) but running it without the --use-conda option.  Running it with --use-conda somehow gives me an "Error in source file definition: must be given as Python string or one of the predefined source file marker types" from snakemake.  Anyways, all good now!

Thanks again,
Tim

**Comment by a-ludi** [comment]
Even the latest release has issues with Python because recent Snakemake versions (installed on host system) require a newer Python version (shipped with Singularity image). This is a rather unfortunate dependency situation that will certainly lead to an never ending stream of issues. Yet, this is how Snakemake makes use of Singularity containers.

Therefore, I will cease to fix this issue. I am working on replacing Snakemake with a custom workflow manager that avoids several issues I faced with Snakemake.
