### ISSUE TITLE
`subprocess.run` got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by Duda5** [a-ludi/dentist#36]
I am trying to run `DENTIST` installed with `conda` on a Linux machine (`mamba` and `snakemake` also installed in the same `env` as `DENTIST`).
My working directory contains 5 files and 2 directories: 
```
short_read_assembly_contig.fa
PacBio_reads.fastq.gz 
Snakefile
snakemake.yml 
dentist.yml
envs\
scripts\
```
I have not modified `dentist.yml` file and the only modifications to `snakemake.yml` I made are file names.

When I try to run it with the following command - `snakemake --configfile=snakemake.yml --use-conda --cores=16`, I get this error:
```
SyntaxError in line 930 of /ANALYSIS1/SRS_genome_asm/Snakefile:
Unexpected keyword container in rule definition (Snakefile, line 930)
```
What can be causing this?

**Comment by Duda5** [comment]
The default version of `snakemake` installed through `conda` was `3.x.x`. 
I have upgraded it to `6.15.5` and now I get a different error (when trying to run `DENTIST` on sample data from provided `dentist-example`):
```
$ snakemake --configfile=snakemake.yml --use-conda --cores=16

Creating conda environment envs/dentist_v4.yml...
Downloading and installing remote packages.
Environment for envs/dentist_v4.yml created (location: .snakemake/conda/f0ae6c9cbf74b9c08f89b3ae9793cc01)
TypeError in line 394 of /ANALYSIS1/SRS_genome_asm/Snakefile:
__init__() got an unexpected keyword argument 'text'
  File "/ANALYSIS1/SRS_genome_asm/Snakefile", line 806, in <module>
  File "/ANALYSIS1/SRS_genome_asm/Snakefile", line 439, in full_validate_dentist_config
  File "/ANALYSIS1/SRS_genome_asm/Snakefile", line 394, in dentist_validate_file
  File "/home/duda5/anaconda3/envs/smake/lib/python3.6/subprocess.py", line 423, in run
```

**Comment by a-ludi** [comment]
Hi Duda5,

glad you could fix the first issue by yourself. The second is related to software versions as well. Apparently, the `text` argument to `subprocess.run` was not part of the API since its introduction. 

Please try fixing it by replacing all occurrences of `text=True` by `universal_newlines=True`, e.g. using

```sh
sed -i 's/test=True/universal_newlines=True/' Snakefile
```

I do not have time to test that fix right now. Please let me know if it works. I will include a bugfix upstream if it does.

**Comment by Duda5** [comment]
Hi @a-ludi, 
Thanks for prompt reply.
I used the command you suggested, but still got the same error.
(A quick search of `Snakemake` with `grep` for `test=True` returns nothing, so I guess nothing was modified with `sed`).

I did, however, found a workaround that allowed me to run `DENTIST` (at least on sample data).
My `base` `conda` environment does not support installation of most new packages (including `mamba` and `snakemake)` due to dozens of conflicts (and unfortunately, I cannot re-install it right now).
It is probably very poor practice, but I will still post here what I did because it somehow worked: 
```
#creating a new conda env with python=3.7 for mamba (lower python versions did not work)
conda create -n dentist python=3.7.0
conda activate dentist
conda install -c conda-forge mamba
#installing snakemake in a sub-environment 
mamba create -c conda-forge -c bioconda -n snakemake snakemake
mamba init 
mamba activate snakemake
conda install -c a_ludi dentist-core 
```
After that, I was able to successfully run `DENTIST` on sample data and all files were "OK" after running `md5sum`.
So I guess the issue was caused by `python=3.6` in the original `conda` environment (which I could not update due to `mamba/snakemake` conflicts).

Eventually, after running `DENTIST` on real data I got another error, but I think I need to improve my assembly and try a few other things first. If I cannot resolve it, I will raise another issue.

**Comment by a-ludi** [comment]
Hi @Duda5 ,

yes, the issue was related to the Python version. Also there was a typo in my sed command. Should have been

```sh
sed -i 's/text=True/universal_newlines=True/' Snakefile
```

Since you got it all running by using Python 3.7, I am going to close this issue. Please feel free to reach out if you have any other issue with DENTIST.
