### ISSUE TITLE
one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!

### ISSUE THREAD

**Issue by plnspineda** [a-ludi/dentist#39]
Hello! Can I ask your help to troubleshoot? I keep having this error at self alignment block. This is one of the error. I have 3Gb genome I'd like to be gap filled with 33x coverage of HiFi reads.

```
Error in rule self_alignment_block:
    jobid: 114
    input: dentist.yml, workdir/sp_buf_purged_scaffolded_chrlevel_draft1.dam, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.bps, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.hdr, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.idx, workdir/.assembly.sp_buf_purged_scaffolded_chrlevel_draft1, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.dust.anno, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.dust.data, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.tan.anno, workdir/.sp_buf_purged_scaffolded_chrlevel_draft1.tan.data
    output: workdir/sp_buf_purged_scaffolded_chrlevel_draft1.10.sp_buf_purged_scaffolded_chrlevel_draft1.12.las, workdir/sp_buf_purged_scaffolded_chrlevel_draft1.12.sp_buf_purged_scaffolded_chrlevel_draft1.10.las
    log: logs/self-alignment.sp_buf_purged_scaffolded_chrlevel_draft1.10.12.log (check log file(s) for error message)
    conda-env: path/to/folder/.snakemake/conda/e844e04141fb5a79087f06209dc3fe6c_
    shell:
        
            {
                cd workdir
                daligner -I '-T8' -l500 -e0.7 -mdust -mtan sp_buf_purged_scaffolded_chrlevel_draft1.10 sp_buf_purged_scaffolded_chrlevel_draft1.12
            } &> logs/self-alignment.sp_buf_purged_scaffolded_chrlevel_draft1.10.12.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 15340668

Error executing rule self_alignment_block on cluster (jobid: 114, external: 15340668, jobscript: path/to/folder/.snakemake/tmp.2nk_qpv5/snakejob.self_alignment_block.114.sh). For error details see the cluster log and the log files of the involved rule(s).
```
Unfortunately, the the logfile has nothing at all besides this :

```
(base) [user@l01 logs]$ cat self-alignment.sp_buf_purged_scaffolded_chrlevel_draft1.log
  Merging 144 files totaling 212,461,282 records
```
Thank you very much!

**Comment by a-ludi** [comment]
Hi,

frankly, I have no clue what may have cause the error. Is there any helpful information from your cluster regarding job 15340668?

The only thing that comes to mind is a lack of memory - even if that seems unlikely. Are you somewhat limited in memory? You may try reducing the block size (e.g. [here](https://github.com/a-ludi/dentist/blob/develop/snakemake/snakemake.yml#L77) and [here](https://github.com/a-ludi/dentist/blob/develop/snakemake/snakemake.yml#L83)) in order to reduce the memory footprint of that command. I would recommend you `rm -rf workdir`  before running the pipeline again.

**Comment by a-ludi** [comment]
Hi @plnspineda, did have have any luck?

**Comment by plnspineda** [comment]
Hi @a-ludi 

I am very sorry I wasn't able to get back soon. I tried reducing the block size but keep getting the same problem. However, it's probably an issue in our server because some blocks gets completed, while the others do not. I am closing this now because I wouldn't be able to explore more on it. Thank you so much for your help, and I apologise, I am not able to give more feedback.
