### ISSUE TITLE
Error: File stdout.fasta, Line 1: First header in fasta file is missing

### ISSUE THREAD

**Issue by aureliendejode** [a-ludi/dentist#40]
Hi,
I am trying to run dentitst and got that error.

File stdout.fasta, Line 1: First header in fasta file is missing

I am thinking it might be because of the names on the contigs in the ref ? My seqeunce names only contains "_" letters and numbers. 

Any idea ?
Thanks for your help

**Comment by aureliendejode** [comment]
Here is my full error message:

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Singularity containers: ignored
Job stats:
job                                                count    min threads    max threads
-----------------------------------------------  -------  -------------  -------------
ALL                                                    1              1              1
collect                                                1              8              8
make_merge_config                                      1              1              1
mark_assembly_preliminary_gap_closed                   1              1              1
mark_assembly_reference                                1              1              1
mask_dust                                              2              1              1
mask_reads                                             1              1              1
mask_self                                              2              1              1
mask_tandem                                            2              1              1
mask_tandem_block                                      2              1              1
merge_insertions                                       1              1              1
preliminary_closed_gaps_bed2mask                       1              1              1
preliminary_gap_closed2dam                             1              1              1
preliminary_gap_closed_vs_reads_alignment              1              1              1
preliminary_gap_closed_vs_reads_alignment_block        1              8              8
preliminary_output                                     1              1              1
process                                                1              8              8
propagate_mask_back_to_reference                       3              1              1
propagate_mask_back_to_reference_block                 3              1              1
propagate_mask_batch                                   3              1              1
propagate_mask_to_reads_block                          3              1              1
reads2db                                               1              1              1
ref_vs_reads_alignment                                 1              1              1
ref_vs_reads_alignment_block                           1              8              8
reference2dam                                          1              1              1
self_alignment                                         2              1              1
self_alignment_block                                   2              8              8
split_preliminary_gap_closed_vs_reads_alignment        1              1              1
tandem_alignment_block                                 2              8              8
unpurged_output                                        1              1              1
validate_regions                                       1              1              1
validate_regions_block                                32              8              8
weak_coverage_mask                                     1              1              1
total                                                 79              1              8

Select jobs to execute...

[Fri Mar 24 16:43:54 2023]
localrule mark_assembly_reference:
    input: /proj/snic2020-6-155/gap_closing_nobackup/Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.fasta
    output: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.assembly.Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17
    jobid: 12
    reason: Missing output files: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.assembly.Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17
    resources: tmpdir=/scratch/36024016

[Fri Mar 24 16:43:54 2023]
localcheckpoint reads2db:
    input: /proj/snic2020-6-155/gap_closing_nobackup/littorina_pacbio_new_pacbio_all_third_lib.fastq
    output: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/littorina_pacbio_new_pacbio_all_third_lib.db, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.littorina_pacbio_new_pacbio_
all_third_lib.bps, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.littorina_pacbio_new_pacbio_all_third_lib.idx
    jobid: 3
    reason: Missing output files: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/littorina_pacbio_new_pacbio_all_third_lib.db
    resources: tmpdir=/scratch/36024016
Downstream jobs will be updated after completion.


[Fri Mar 24 16:43:54 2023]
localcheckpoint reference2dam:
    input: /proj/snic2020-6-155/gap_closing_nobackup/Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.fasta
    output: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.dam, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.Lsax_genome_CLR_HiC_c
urated_freeze_1_2023_02_17.bps, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.hdr, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.
Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.idx
    jobid: 2
    reason: Missing output files: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.dam
    resources: tmpdir=/scratch/36024016
Downstream jobs will be updated after completion.

Touching output file /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.assembly.Lsax_genome_CLR_HiC_curated_freeze_1_2023_02_17.
[Fri Mar 24 16:43:54 2023]
Finished job 12.
1 of 79 steps (1%) done
[Fri Mar 24 16:43:55 2023]
Error in rule reads2db:
    jobid: 3
    input: /proj/snic2020-6-155/gap_closing_nobackup/littorina_pacbio_new_pacbio_all_third_lib.fastq
    output: /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/littorina_pacbio_new_pacbio_all_third_lib.db, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.littorina_pacbio_new_pacbio_
all_third_lib.bps, /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/.littorina_pacbio_new_pacbio_all_third_lib.idx
    conda-env: /crex/proj/snic2020-6-155/gap_closing_nobackup/dentist/dentist_root/.snakemake/conda/72711f497d278812653381ae144ea3d8_
    shell:
        fold -w9998 /proj/snic2020-6-155/gap_closing_nobackup/littorina_pacbio_new_pacbio_all_third_lib.fastq | fasta2DB -i /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/littorina_pacbio_new_
pacbio_all_third_lib.db && DBsplit -x1000 -a -s200 /proj/snic2020-6-155/gap_closing_nobackup/dentist/workdir/littorina_pacbio_new_pacbio_all_third_lib.db
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Fri Mar 24 16:44:44 2023]
Finished job 2.
2 of 79 steps (3%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-24T164351.424234.snakemake.log

**Comment by a-ludi** [comment]
Hi @aureliendejode, please split off the FASTA from `/proj/snic2020-6-155/gap_closing_nobackup/littorina_pacbio_new_pacbio_all_third_lib.fastq` sequence and use that instead. DENTIST does not support `.fastq` files.

Cheers!
