### ISSUE TITLE
Rerun after stop due to time limit

### ISSUE THREAD

**Issue by aureliendejode** [a-ludi/dentist#41]
Hello,

I am ran the snakemake pipeline from on a slurm cluster in a single job using sbatch.
It stopped due to time limit and now when I try to rerun it, it just list a bunch of job and stops again without clear explanation.
Any idea what is going on ?

Here is my script

snakemake --configfile=snakemake.yml --use-conda --cores=all --rerun-incomplete --unlock
snakemake --configfile=snakemake.yml --use-conda --cores=all --rerun-incomplete

**Comment by a-ludi** [comment]
AFAIK there is no need for `--rerun-incomplete`. Actually, I think that might be the culprit. 

Please adjust the cluster config to increase time limits.

**Comment by aureliendejode** [comment]
Hi,
So I removed --rerun-incomplete and started from scratch with more resources and it ran well.
I am wondering now at what output should I look to know how many gaps were closed and how they were validated ?
Is it all in the report.json ?

Best

**Comment by a-ludi** [comment]
Glad it worked!

You will want to look at the `*.closed-gaps.bed` first. It describes the locations of closed gaps in the result FASTA – one line per closed gap. The `*.agp` provide a little more information how the assembly is structured but is much harder to read. 

The `report.json` provides details on the results of the automatic validation. It may be useful if you have gap a that was not closed and are wondering why. But its not the only place to - look for, see #33.

**Comment by a-ludi** [comment]
The main reason for this issue is fixed so I will close this issue. Please feel free to open a new one if you need further help or guidance.
