### ISSUE TITLE
Example fails with Colon expected after keyword global_conda. (Snakefile, line 103)

### ISSUE THREAD

**Issue by faulk-lab** [a-ludi/dentist#43]
Trying to run the example on a fresh Ubuntu 22.04 install. I ran the following and get the following error:

```
# install Dentist
mamba create -n dentist -c a_ludi -c bioconda dentist-core
mamba activate dentist
mamba install -c conda-forge -c bioconda snakemake

#Get example data
wget https://github.com/a-ludi/dentist/releases/download/v4.0.0/dentist-example.tar.gz
tar -xzf dentist-example.tar.gz
cd dentist-example

# run the workflow
PATH="$PWD/bin:$PATH" snakemake --configfile=snakemake.yml --cores=all
```

I get the error:
```SyntaxError in file /home/minknow/Desktop/p2_runs/soybean_leafminer/dentist-example/Snakefile, line 103:
Colon expected after keyword global_conda. (Snakefile, line 103)
```

Any suggestions?

**Comment by pants08** [comment]
Hi, I ran into the same problem as you did, have you managed to solve the problem yet?

**Comment by a-ludi** [comment]
Hi, I am sorry but I have no idea. Probably, it has something to do with changing versions of snakemake or Python.

**Comment by a-ludi** [comment]
@pants08 @faulk-lab Sadly, I have no record of the Python version I used to use. Please try using Python 3.8, 3.9 or 3.10.

**Comment by estolle** [comment]
thanks for the hint

I had the same problem (with python 3.12) and eventually used successfully python 3.10:
```
mamba create -n dentist2 -c a_ludi -c bioconda -c conda-forge dentist-core python==3.10 snakemake
conda activate dentist2
snakemake --configfile=snakemake.yml --use-conda --cores=50
```
