### ISSUE TITLE
Damapper command fails

### ISSUE THREAD

**Issue by Tierhon** [a-ludi/dentist#7]
Hi,
thank you for dentist, it is an intriguing tool.

However, it is a bit annoying for me. I keep getting errors like the one below, without any useful information.
```
damapper: Command Failed:
              LAmerge  -a reference.reads.439 /cluster/work/users/olekto/tmp/damapper.81025/reference.reads.439.R@.S.las
```
Or
```
LAmerge: Did not write all records to reference.reads.426 (8035)

damapper: Command Failed:
              LAmerge  -a reference.reads.426 /tmp/damapper.69457/reference.reads.426.R@.S.las
```

I wondered if the tmp dir was too small, so I set that to a shared folder that can contain multiple terabytes, so I doubt that is the issue anymore. 

Some partitions go through fine, however, it is only a handful before one throws an error. 

Is there a way to get more useful debugging information? So that I can know how the commands fail and can address that issue?

Thank you. 

Sincerely,
Ole

**Comment by a-ludi** [comment]
Hi Ole,

I am aware of this bug but have not found a solution, yet. Also, the author of damapper/daligner is informed about the bug.

I encountered this particular bug only recently, so I am positive it can be resolved by a certain combination of versions of `damapper` and `LAmgere` (contained in daligner package). I will probably find a quick fix until the end of this week and keep you updated.

**Comment by a-ludi** [comment]
So, the bug is introduced by a [new feature in LAsort](https://github.com/thegenemyers/DALIGNER/commit/477d5b92459c7e22baf2e15af712b70ee54c838b) that removes duplicates automatically while sorting. Damapper will probaly need some adjustments.

For the time being, I resorted to using [daligner as of 2020-01-15](https://github.com/thegenemyers/DALIGNER/commit/c2b47da6b3c94ed248a6be395c5b96a4e63b3f63).

**Comment by a-ludi** [comment]
This should be documented in the dependencies section of the README.

**Comment by a-ludi** [comment]
Documentation added. I will keep this issue open as a reminder that this might get a proper fix sometime in the future.

**Comment by Tierhon** [comment]
Great, 
thank you Arne.

Ole

**Comment by cassondranewman** [comment]
In the dentist readme, daligner >=2020-07-27. I have daligner/2020.07.27 and dentist is still failing on: 

damapper: Command Failed:
              LAmerge  -a XX.raw_subreads.308 /local/bgfs/cassie.newman/5138508/damapper.94044/XX.raw_subreads.308.R@.S.las

Should I just use daligner version 2020-01-15?

**Comment by a-ludi** [comment]
@cassondranewman Sorry, for the late answer. Yes, please try the version 2020-01-15 of daligner.
