### ISSUE TITLE
dentist collect v1.0.0-beta.3 requires DAScover from DASCRUBBER which failed to compile.

### ISSUE THREAD

**Issue by BradleyRan** [a-ludi/dentist#8]
dentist collect v1.0.0-beta.3 requires DAScover from DASCRUBBER.  DAScover.c failed to compile.  

DAScover.c:119:27: error: ‘DB_CSS’ undeclared (first use in this function)
     if ((Reads[j].flags & DB_CSS) == 0)

(snakemake) [randy.bradley@ceres dentist-test]$ cat logs/collect.log 
Error: missing external tools:
- DAScover (part of `DASCRUBBER`; see https://github.com/thegenemyers/DASCRUBBER)
- DASqv (part of `DASCRUBBER`; see https://github.com/thegenemyers/DASCRUBBER)

Check your PATH and/or install the required software.

**Comment by a-ludi** [comment]
Oh no, still that typo. Please just run `sed -i 's/DB_CSS/DB_CCS/' *.{h,c}` in the root of the DASCRUBBER repo. This should fix the compilation.

**Comment by BradleyRan** [comment]
Confirming that worked well.  Thanks!
